### PR TITLE
Add chapter on ABC

### PR DESCRIPTION
**Pull request by gadilashashank**
Some files in Assembly language were changed that included typos and missing words. My opinion is that no editor review is required for changes in assembly.

### CODE REVIEW

**Comment by gadilashashank** [comment]
Oh fuck. I did not change summary.md Will change after build

**Comment by gadilashashank** [comment]
@ODXT I've re-written the CONTRIBUTING.md file and I want you to review it. @Skayo Need help with build rules thingy in the end. @FilipeRamalho Could you review the grammar and structure?

**Comment by Skayo** [comment]
Okay NOW rules are good to go

**Comment by gadilashashank** [comment]
@Skayo any grammar changes?

**Comment by Skayo** [comment]
No didn't check

**Comment by gadilashashank** [comment]
It's ok. I don't think there would be any though I'm open to changes. Waiting for @ODXT to approve the contributing guide. @Skayo will you just check the grammar in the ABC chapter? So that the whole thing can be merged after approval.

**Comment by Skayo** [comment]
After a shitload of small commits. Done now

**Pull request merged**
