### PR TITLE
Modify badge links and remove poll

### PR DESCRIPTION
**Pull request by gadilashashank**
Title says all. Changed "devRant-Squad" in all links to "devRant-Community" to get the badges working again and since the title is decided to "A Ginormous..." the poll has also been removed.

### CODE REVIEW

**Comment by Skayo** [comment]
can't modify for a single file

**Comment by gadilashashank** [comment]
Merge it?

**Comment by Skayo** [comment]
No wait just add this to the beginning of the README:
``<!-- markdownlint-disable MD033 -->``

**Comment by Skayo** [comment]
Should work.

**Comment by gadilashashank** [comment]
Adding

**Comment by Skayo** [comment]
looks good. Now just add a newline after the header

**Comment by gadilashashank** [comment]
Yay closing

**Pull request merged**
