### PR TITLE
Add chapter on assembly and python

### PR DESCRIPTION
**Pull request by gadilashashank**
Major fuck up in previous pull.

### CODE REVIEW

**Comment by gadilashashank** [comment]
Cleaned commit tree.

**Comment by gadilashashank** [comment]
@Skayo thanks for the commas and quotes. I don't understand the difference between the ones used by you and me but let them stay

**Comment by Skayo** [comment]
(Sorry for doing a lot of commits, cannot amend in web version)
I fixed the
- quotes (Use “” instead of ""; more book-likely)
- grammar (What I found)
- typos (Found a few)

I didn't check structure or general spelling (sentences).

**Comment by gadilashashank** [comment]
@Skayo if you haven't noticed I'm a part of the editing team :) anyways I'm welcome for suggestions..

**Pull request merged**
